### PR TITLE
Simplifying template source check

### PR DESCRIPTION
**Pull request by howardroark**
@jedwards1211 I'm moving this here from the other PR.  Could you explain it here a little more.

Thanks!

### CODE REVIEW

**Comment by jedwards1211** [comment]
You know, I should make it more general than just checking for `git@github.com`.  From `git help clone`:

>       An alternative scp-like syntax may also be used with the ssh protocol:
>       * [user@]host.xz:path/to/repo.git/

**Comment by jedwards1211** [comment]
I assume it's not possible to clone private repos via `https://github.com`, and one has to use `git@github.com:...` or `ssh://` URLs.  But I could be wrong.

**Comment by jedwards1211** [comment]
Considering the variety of URLs git accepts, I think it might be best to assume anything that isn't a GitHub URL or directory is a git URL and let git error out if it's invalid.

**Comment by howardroark** [comment]
Yeah `https` works with git cli. That check already accounts for those cases. 

Though yeah... it kinda makes sense to just treat everything as git url after the first two checks.

**Comment by jedwards1211** [comment]
Yeah, looks good to me

**Review by jedwards1211 — APPROVED** [review]
I haven't actually used this review interface before

**Comment by howardroark** [comment]
Works pretty well :)

**Pull request merged**
