### PR TITLE
Add `merge` option to schema

### LINKED ISSUE #44: Add `merge` option to schema
The idea here is to add a new "step" which merges the data of json (or other) object files. The first file in each array being the file to write to.

```
{
  merge: [
    ['package.json', 'PROJECT-package.json']
  ]
}
```

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #44

### CODE REVIEW

**Comment by howardroark** [comment]
This is great!  Does it merge any number of files in the array?

The one thing I would ask is if would be possible to work with `extend` vs adding the new `lodash.merge` package?

**Review by howardroark — APPROVED** [review]

**Comment by jedwards1211** [comment]
Yes, one of my tests merges 3 files.
Ah, I didn't know that `extend` has a `deep` option.  One moment...

**Comment by jedwards1211** [comment]
Okay, I made those changes.  If CI passes, it's ready!

**Comment by howardroark** [comment]
Done! Thanks for this!

**Comment by jedwards1211** [comment]
Yeah, you're welcome!

**Pull request merged**
